import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Abhaya_Libre } from "next/font/google";
import { Footer } from "@/components/Footer";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
});

const abhaya = Abhaya_Libre({
  variable: "--font-abhaya",
  subsets: ["latin"],
  weight: ["800"],
  display: "swap",
});

const bwdiagrid = localFont({
  src: "./BwDiagrid-Regular.woff",
  display: "swap",
  variable: "--font-bwdiagrid",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bwdiagrid.variable} ${abhaya.variable} ${raleway.variable} antialiased`}
      >
        <NavBar />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
