import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";

const bwdiagrid = localFont({
  src: "./BwDiagrid-Regular.woff",
  display: "swap",
  variable: "--font-bwdiagrid",
});
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bwdiagrid.variable} antialiased`}
      >
        <NavBar />
        <main> {children}</main>
      </body>
    </html>
  );
}
